# Generated by Django 4.1.3 on 2022-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
